
%define	v0r		rax
%define	v1r		rdi
%define	v2r		rsi
%define	v3r		rdx
%define	v4r		r10
%define	v5r		r8
%define	v6r		r9


%define	v0x		eax
%define	v1x		edi
%define	v2x		esi
%define	v3x		edx
%define	v4x		r10d
%define	v5x		r8d
%define	v6x		r9d

%define	v0		ax
%define	v1		di
%define	v2		si
%define	v3		dx
%define	v4		r10w
%define	v5		r8w
%define	v6		r9w

%define	v0l		al
%define	v1l		dil
%define	v2l		sil
%define	v3l		dl
%define	v4l		r10b
%define	v5l		r8b
%define	v6l		r9b

%define	max		rax
%define	mbx		rbx
%define	mcx		rcx
%define	mdx		rdx
%define	mbp		rbp
%define	msi		rsi
%define	mdi		rdi
%define	msp		rsp
%define	mr8		r8
%define	mr9		r9
%define	mr10	r10
%define	mr11	r11
%define	mr12	r12
%define	mr13	r13
%define	mr14	r14
%define	mr15	r15
%define	ptr		resq
%define	small	resb
%define	big		resq
%define	ptr_size 8

%define	stdin		0
%define	stdout		1
%define	stderr		2

%define	sys_exit		60
%define	sys_write		1
%define	sys_mmap		9

%define	@start			_start




